/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
import java.io.BufferedReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class BalanceInquery extends javax.swing.JFrame {

    /**
     * Creates new form BalanceInquery
     */
    public static String acc;
    public BalanceInquery(String ac) {
        acc=ac;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        backtotransaction = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pin1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(125, 60, 152));
        jPanel4.setPreferredSize(new java.awt.Dimension(1241, 860));
        jPanel4.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(346, 329, 296, 35);

        exit.setBackground(new java.awt.Color(102, 102, 102));
        exit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(490, 670, 330, 59);

        backtotransaction.setBackground(new java.awt.Color(51, 51, 51));
        backtotransaction.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 28)); // NOI18N
        backtotransaction.setForeground(new java.awt.Color(153, 255, 255));
        backtotransaction.setText("Back to Transaction");
        backtotransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        backtotransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtotransactionActionPerformed(evt);
            }
        });
        jPanel4.add(backtotransaction);
        backtotransaction.setBounds(810, 520, 390, 59);

        Deposit.setBackground(new java.awt.Color(51, 51, 51));
        Deposit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit.setForeground(new java.awt.Color(153, 255, 255));
        Deposit.setText("Cheack Balance");
        Deposit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });
        jPanel4.add(Deposit);
        Deposit.setBounds(70, 510, 400, 64);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pin Number:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(250, 290, 310, 65);

        pin1.setBackground(new java.awt.Color(153, 255, 204));
        pin1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        pin1.setBorder(null);
        pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin1ActionPerformed(evt);
            }
        });
        jPanel4.add(pin1);
        pin1.setBounds(570, 290, 430, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0_MAIN_170518_GBR_DepositMoney_1920x1080.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 1241, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you want to Exit!");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backtotransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotransactionActionPerformed
        // TODO add your handling code here:
        Transaction rgf=new Transaction(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
         return ;
    }//GEN-LAST:event_backtotransactionActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:

        String account,pin;
        account=acc;
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                if(c==1){
                    break;
                }
                c++;
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
                     BufferedReader bf1 = null;
        try {
            bf1 = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c1=0;
        String d = null;
        try {
            while((d=bf1.readLine())!=null)
            {
              
                c1++; 
                if(c1==3){
                    break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf1.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
            
            
            JOptionPane.showMessageDialog(null,"Total Available balance "+d+" ");
            BalanceInquery rgf1=new BalanceInquery(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;

        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            BalanceInquery rgf1=new BalanceInquery(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

    }//GEN-LAST:event_DepositActionPerformed

    private void pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String ac) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceInquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceInquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceInquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceInquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceInquery(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deposit;
    private javax.swing.JButton backtotransaction;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pin1;
    // End of variables declaration//GEN-END:variables
}
