


import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class FastCash1 extends javax.swing.JFrame {
   
    /**
     * Creates new form FastCash
     */
String uemail="",utext="";
    class Main1
{
    String  d_email = "mh715360@gmail.com",
            d_password = "97325060",
            d_host = "smtp.gmail.com",
            d_port  = "465",
            m_to = uemail,
            m_subject = "Withdraw Amount",
            m_text = utext;

    public Main1()
    {
        Properties props = new Properties();
        props.put("mail.smtp.user", d_email);
        props.put("mail.smtp.host", d_host);
        props.put("mail.smtp.port", d_port);
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", d_port);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");

        SecurityManager security = System.getSecurityManager();

        try
        {
            Authenticator auth = new SMTPAuthenticator();
            Session session = Session.getInstance(props, auth);
            session.setDebug(true);
            MimeMessage msg = new MimeMessage(session);
            msg.setText(m_text);
            msg.setSubject(m_subject);
            msg.setFrom(new InternetAddress(d_email));
            msg.addRecipient(Message.RecipientType.TO, new InternetAddress(m_to));
            Transport.send(msg);
        }
        catch (Exception mex)
        {
            mex.printStackTrace();
        } 
    }

    

    private class SMTPAuthenticator extends javax.mail.Authenticator
    {
        public PasswordAuthentication getPasswordAuthentication()
        {
            return new PasswordAuthentication(d_email, d_password);
        }
    }
}
    
   int bal=0;
   public static String acc;   
   public FastCash1(String ac) {
        acc=ac;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Deposit = new javax.swing.JButton();
        Deposit1 = new javax.swing.JButton();
        Deposit2 = new javax.swing.JButton();
        Deposit3 = new javax.swing.JButton();
        Deposit4 = new javax.swing.JButton();
        Deposit5 = new javax.swing.JButton();
        Deposit6 = new javax.swing.JButton();
        Deposit7 = new javax.swing.JButton();
        backtotransaction = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pin1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setLayout(null);

        Deposit.setBackground(new java.awt.Color(51, 51, 51));
        Deposit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit.setForeground(new java.awt.Color(153, 255, 255));
        Deposit.setText("500");
        Deposit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit);
        Deposit.setBounds(120, 260, 400, 57);

        Deposit1.setBackground(new java.awt.Color(51, 51, 51));
        Deposit1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit1.setForeground(new java.awt.Color(153, 255, 255));
        Deposit1.setText("30000");
        Deposit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit1ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit1);
        Deposit1.setBounds(701, 340, 400, 64);

        Deposit2.setBackground(new java.awt.Color(51, 51, 51));
        Deposit2.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit2.setForeground(new java.awt.Color(153, 255, 255));
        Deposit2.setText("1000");
        Deposit2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit2ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit2);
        Deposit2.setBounds(120, 340, 400, 64);

        Deposit3.setBackground(new java.awt.Color(51, 51, 51));
        Deposit3.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit3.setForeground(new java.awt.Color(153, 255, 255));
        Deposit3.setText("40000");
        Deposit3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit3ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit3);
        Deposit3.setBounds(701, 435, 400, 64);

        Deposit4.setBackground(new java.awt.Color(51, 51, 51));
        Deposit4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit4.setForeground(new java.awt.Color(153, 255, 255));
        Deposit4.setText("5000");
        Deposit4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit4ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit4);
        Deposit4.setBounds(120, 440, 400, 64);

        Deposit5.setBackground(new java.awt.Color(51, 51, 51));
        Deposit5.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit5.setForeground(new java.awt.Color(153, 255, 255));
        Deposit5.setText("10000");
        Deposit5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit5ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit5);
        Deposit5.setBounds(120, 540, 400, 64);

        Deposit6.setBackground(new java.awt.Color(51, 51, 51));
        Deposit6.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit6.setForeground(new java.awt.Color(153, 255, 255));
        Deposit6.setText("20000");
        Deposit6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit6ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit6);
        Deposit6.setBounds(701, 258, 400, 64);

        Deposit7.setBackground(new java.awt.Color(51, 51, 51));
        Deposit7.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        Deposit7.setForeground(new java.awt.Color(153, 255, 255));
        Deposit7.setText("50000");
        Deposit7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        Deposit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deposit7ActionPerformed(evt);
            }
        });
        jPanel1.add(Deposit7);
        Deposit7.setBounds(701, 541, 400, 64);

        backtotransaction.setBackground(new java.awt.Color(51, 51, 51));
        backtotransaction.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 28)); // NOI18N
        backtotransaction.setForeground(new java.awt.Color(153, 255, 255));
        backtotransaction.setText("Back to Transaction");
        backtotransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        backtotransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtotransactionActionPerformed(evt);
            }
        });
        jPanel1.add(backtotransaction);
        backtotransaction.setBounds(60, 710, 450, 68);

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(720, 700, 430, 70);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Pin NUmber:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 100, 450, 50);

        pin1.setBackground(new java.awt.Color(153, 255, 204));
        pin1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        pin1.setBorder(null);
        jPanel1.add(pin1);
        pin1.setBounds(570, 100, 470, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmmmm.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-2, -3, 1240, 870);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1235, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String depo_account="";
    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:
       
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          

         
                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="500";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
           FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
    }//GEN-LAST:event_DepositActionPerformed

    private void Deposit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit1ActionPerformed
        // TODO add your handling code here:

        
                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="30000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
        
        
        
    }//GEN-LAST:event_Deposit1ActionPerformed

    private void Deposit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit2ActionPerformed
        // TODO add your handling code here:

       
                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="1000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
           FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
    }//GEN-LAST:event_Deposit2ActionPerformed

    private void Deposit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit3ActionPerformed
        // TODO add your handling code here:

        
                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="40000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
           FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
    }//GEN-LAST:event_Deposit3ActionPerformed

    private void Deposit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit4ActionPerformed
        // TODO add your handling code here:

                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="5000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
        
    }//GEN-LAST:event_Deposit4ActionPerformed

    private void Deposit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit5ActionPerformed
        // TODO add your handling code here:

                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="10000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
        
    }//GEN-LAST:event_Deposit5ActionPerformed

    private void Deposit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit6ActionPerformed
        // TODO add your handling code here:

                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="20000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
     
    }//GEN-LAST:event_Deposit6ActionPerformed

    private void Deposit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deposit7ActionPerformed
        // TODO add your handling code here:

         
                String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String account,pin,transaction;
       
        depo_account=acc+"t_h"+".txt";
        account=acc;
        transaction=acc;
        
        
        pin=pin1.getText();
        account=account+".txt";
        File f1 = new File(account);
        if(!f1.exists())
        {
            JOptionPane.showMessageDialog(null, "The account is not exits !!!");
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
        }

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                c++;
                if(c==2){
                    break;
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(s1.equals(pin))
        {
            
            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                        uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            //prompt for a line in file to edit
            String lineToEdit1=pin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            String d="50000";
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "Withdraw Unsuccessful!!\nInsufficient Balance");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
                bal = Integer.parseInt(s2)-Integer.parseInt(d);
             String t2=ctime+" "+d+"Taka Has Been Withdrawn From Your Account"+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
             
            
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null,"Withdraw amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
            
            utext="Dear Sir,your account number "+acc+" debited (ATM Cash Withdrawl) by BDT "+d+".Now current account balance is "+bal+".";
            FastCash1.Main1 blah = new FastCash1.Main1();
            FastCash1 rgf1=new FastCash1(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             return ;
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            FastCash1 rgf2=new FastCash1(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        } 
        
        
      
    }//GEN-LAST:event_Deposit7ActionPerformed

    private void backtotransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotransactionActionPerformed
        // TODO add your handling code here:
        Transaction rgf=new Transaction(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtotransactionActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you want to Exit!");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash1(acc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deposit;
    private javax.swing.JButton Deposit1;
    private javax.swing.JButton Deposit2;
    private javax.swing.JButton Deposit3;
    private javax.swing.JButton Deposit4;
    private javax.swing.JButton Deposit5;
    private javax.swing.JButton Deposit6;
    private javax.swing.JButton Deposit7;
    private javax.swing.JButton backtotransaction;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pin1;
    // End of variables declaration//GEN-END:variables
}
