
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class MiniStatement extends javax.swing.JFrame {

    /**
     * Creates new form MiniStatement
     */
    public static String acc;
    public MiniStatement(String ac) {
        acc=ac;
       initComponents();
        String account,pin;
        account =acc;
        account=account+".txt";
        File f1 = new File(account);
        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                if(c==1){
                    break;
                }
                c++;
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        

            BufferedReader bf1 = null;
            try {
                bf1 = new BufferedReader(new FileReader(account));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            int c1=0;
            String d = null;
            String p1 = null,p2 = null,p3 = null,p4 = null,p5 = null,p6 = null,p7 = null;
            try {
                while((d=bf1.readLine())!=null)
                {

                    c1++;
                    if(c1==1){
                        p1=d;
                    }
                    else if(c1==2){
                        p2=d;
                    }
                    else if(c1==3){
                        p3=d;
                    }
                    else if(c1==4){
                        p4=d;
                    }
                    else if(c1==5){
                        p5=d;
                    }
                    else if(c1==6){
                        p6=d;
                    }
                    else if(c1==7){
                        p7=d;
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                bf1.close();
            } catch (IOException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            //JOptionPane.showMessageDialog(null,"\n\n\n\n        Full Name : "+p1+"                                             \n        Phone : "+p3+"                       \n        E-mail : "+p4+"                       \n        Birth Date : "+p5+"                       \n        Balance : "+p6+"                       \n        Address : "+p7+"                       \n\n\n");
            account1.setText(acc);
            name.setText(p1);
            phone.setText(p4);
            email.setText(p5);
            birthdate.setText(p6);
            address.setText(p7);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        backtotransaction = new javax.swing.JButton();
        account1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        birthdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(125, 60, 152));
        jPanel4.setPreferredSize(new java.awt.Dimension(1241, 860));
        jPanel4.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(196, 396, 296, 35);

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(116, 749, 387, 59);

        backtotransaction.setBackground(new java.awt.Color(51, 51, 51));
        backtotransaction.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 24)); // NOI18N
        backtotransaction.setForeground(new java.awt.Color(153, 255, 255));
        backtotransaction.setText("Back to Transaction");
        backtotransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        backtotransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtotransactionActionPerformed(evt);
            }
        });
        jPanel4.add(backtotransaction);
        backtotransaction.setBounds(790, 750, 388, 59);

        account1.setBackground(new java.awt.Color(153, 255, 204));
        account1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        account1.setBorder(null);
        account1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account1ActionPerformed(evt);
            }
        });
        jPanel4.add(account1);
        account1.setBounds(460, 100, 680, 49);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Account No:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(160, 100, 290, 37);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Name:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(160, 180, 207, 41);

        name.setBackground(new java.awt.Color(153, 255, 204));
        name.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        name.setBorder(null);
        jPanel4.add(name);
        name.setBounds(460, 180, 680, 51);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Birth Date:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(160, 430, 283, 41);

        email.setBackground(new java.awt.Color(153, 255, 204));
        email.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        email.setBorder(null);
        jPanel4.add(email);
        email.setBounds(460, 350, 680, 51);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Phone:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(160, 260, 207, 41);

        phone.setBackground(new java.awt.Color(153, 255, 204));
        phone.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        phone.setBorder(null);
        jPanel4.add(phone);
        phone.setBounds(460, 260, 680, 51);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Email:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(160, 350, 207, 41);

        birthdate.setBackground(new java.awt.Color(153, 255, 204));
        birthdate.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        birthdate.setBorder(null);
        jPanel4.add(birthdate);
        birthdate.setBounds(460, 430, 680, 51);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Address:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(160, 540, 243, 52);

        address.setBackground(new java.awt.Color(153, 255, 204));
        address.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        address.setBorder(null);
        jPanel4.add(address);
        address.setBounds(460, 540, 680, 140);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designbig.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 1240, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you want to Exit!");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backtotransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtotransactionActionPerformed
        // TODO add your handling code here:
        Transaction rgf=new Transaction(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
         return ;
    }//GEN-LAST:event_backtotransactionActionPerformed

    private void account1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String ac) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MiniStatement(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account1;
    private javax.swing.JTextField address;
    private javax.swing.JButton backtotransaction;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField email;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
