


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class moneytransfer extends javax.swing.JFrame {

    /**
     * 
     */
    
    
    
        
     String uemail="",utext="";

    /**
     * Creates new form DepositeMoney
     */
    
 
    
    
    
    
    int bal=0;
    public static String acc;
    public moneytransfer(String ac) {
        acc=ac;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        balancesend = new javax.swing.JButton();
        reciverac = new javax.swing.JTextField();
        enteramount = new javax.swing.JTextField();
        pin = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setIconImages(null);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1241, 860));
        setMinimumSize(new java.awt.Dimension(1241, 860));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Recipient Account Number:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 260, 610, 57);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Amount:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 360, 610, 50);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Pin Number:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 450, 610, 50);

        balancesend.setBackground(new java.awt.Color(51, 51, 51));
        balancesend.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        balancesend.setForeground(new java.awt.Color(102, 255, 204));
        balancesend.setText("SEND");
        balancesend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        balancesend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancesendActionPerformed(evt);
            }
        });
        getContentPane().add(balancesend);
        balancesend.setBounds(680, 590, 470, 70);

        reciverac.setBackground(new java.awt.Color(153, 255, 204));
        reciverac.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        reciverac.setForeground(new java.awt.Color(51, 0, 51));
        reciverac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciveracActionPerformed(evt);
            }
        });
        getContentPane().add(reciverac);
        reciverac.setBounds(720, 260, 415, 60);

        enteramount.setBackground(new java.awt.Color(153, 255, 204));
        enteramount.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        getContentPane().add(enteramount);
        enteramount.setBounds(720, 350, 415, 60);

        pin.setBackground(new java.awt.Color(153, 255, 204));
        pin.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        getContentPane().add(pin);
        pin.setBounds(720, 450, 415, 60);

        jButton4.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 255, 255));
        jButton4.setText("BACK TO TRANSACTION");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 590, 480, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneytransfer.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1220, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String depo_account="";
    
    
    private void balancesendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancesendActionPerformed
        // TODO add your handling code here:
            String ctime="";
      SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        
        String transaction="";
       
        depo_account=acc+"t_h"+".txt";
        
        transaction=acc;
        
        
        String account1,pin1,account2;
        String d=enteramount.getText();
        account1=acc;
         account1=account1+".txt";
        pin1=pin.getText();
        account2=reciverac.getText();
        account2=account2+".txt";
        File f1 = new File(account1);
        File f2 = new File(account2);
        if(!f2.exists())
        {
            JOptionPane.showMessageDialog(null, "The  Reciepient account does not exits !!!");
            moneytransfer rgf1=new moneytransfer(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();  
           return ;
        }
        

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader(account1));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        int c=0;
        String s1 = null;
        try {
            while((s1=bf.readLine())!=null)
            {
                if(c==1){
                    break;
                }
                c++;
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bf.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        if(s1.equals(pin1))
        {

            int c2=0;
            String s2 = null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account1;
            Scanner fileToRead = null;

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==3)
                    s2=line;
                    if(c2==5)
                      uemail=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

            
            //prompt for a line in file to edit
            String lineToEdit1=pin1;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

            
            if(Integer.parseInt(s2)<Integer.parseInt(d))
            {
                      JOptionPane.showMessageDialog(null, "MoneyTransfer Unsuccessful!!\nInsufficient Balance");
            moneytransfer rgf2=new moneytransfer(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
            }
            else
            {
            bal=Integer.parseInt(s2)-Integer.parseInt(d);
            
                    String t2=ctime+" "+d+" Taka Has Been Transferred To Your Account No : "+reciverac.getText()+ System.lineSeparator();
              try{
                   BufferedWriter mahedi = new BufferedWriter( new FileWriter(depo_account, true));
                   mahedi.write(t2);
                   mahedi.close();
              }catch(IOException e)
              {
                  e.printStackTrace();
              }
            
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, pin1);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            utext="Dear Sir,your account number "+acc+" debited (Cash Withdrawal) by BDT "+d+".Now current account balance is "+bal+".\n"+"In account no "+reciverac.getText()+" crdeited (Cash Deposit) by BDT "+d;
            
            JOptionPane.showMessageDialog(null,"Transfer amount "+d+" Successfully!!!/nNow current Balance is "+bal+".");
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            moneytransfer rgf2=new moneytransfer(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        }
        
        
        
        
            class Main1
{
    String  d_email = "mh715360@gmail.com",
            d_password = "97325060",
            d_host = "smtp.gmail.com",
            d_port  = "465",
            m_to = uemail,
            m_subject = "Transfer Amount",
            m_text = utext;

    public Main1()
    {
        Properties props = new Properties();
        props.put("mail.smtp.user", d_email);
        props.put("mail.smtp.host", d_host);
        props.put("mail.smtp.port", d_port);
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", d_port);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");

        SecurityManager security = System.getSecurityManager();

        try
        {
            Authenticator auth = new SMTPAuthenticator();
            Session session = Session.getInstance(props, auth);
            session.setDebug(true);
            MimeMessage msg = new MimeMessage(session);
            msg.setText(m_text);
            msg.setSubject(m_subject);
            msg.setFrom(new InternetAddress(d_email));
            msg.addRecipient(Message.RecipientType.TO, new InternetAddress(m_to));
            Transport.send(msg);
        }
        catch (Exception mex)
        {
            mex.printStackTrace();
        } 
    }

    

    class SMTPAuthenticator extends javax.mail.Authenticator
    {
        public PasswordAuthentication getPasswordAuthentication()
        {
            return new PasswordAuthentication(d_email, d_password);
        }
    }
}
             Main1 blah = new Main1();
        
        
        
        

        if(s1.equals(pin1))
        {

            int c2=0;
            String s2 = null,rpin=null;
            StringBuffer stringBufferOfData = new StringBuffer();
            String filename = null;
            Scanner sc = new Scanner(System.in);
            filename=account2;
            Scanner fileToRead = null;
            

            try {
                fileToRead = new Scanner(new File(filename)); //point the scanner method to a file
                //check if there is a next line and it is not null and then read it in
                for (String line; fileToRead.hasNextLine() && (line = fileToRead.nextLine()) != null; ) {
                    //print each line as its read
                    c2++;
                    if(c2==2)
                        rpin=line;
                    if(c2==3)
                    s2=line;
                    stringBufferOfData.append(line).append("\r\n");//this small line here is to appened all text read in from the file to a string buffer which will be used to edit the contents of the file
                }
                fileToRead.close();//this is used to release the scanner from file
            } catch (FileNotFoundException ex) {//if the file cannot be found an exception will be thrown
                System.out.println("The file " + filename + " could not be found! " + ex.getMessage());
            } finally {//if an error occurs now we close the file to exit gracefully
                fileToRead.close();
            }

             
            
            
            String lineToEdit1=rpin;
            String lineToEdit2 = s2;//read the line to edit
            //prompt for a line in file to replace

           
            bal=Integer.parseInt(s2)+Integer.parseInt(d);
            String p="|";
            String replacementText1 = p;
            String replacementText2 = Integer.toString(bal);//read the line to replace
            int si1 = stringBufferOfData.indexOf(lineToEdit1);
//now we get the starting point of the text we want to edit
            int ei1 = si1 + lineToEdit1.length();
            //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing
            stringBufferOfData.replace(si1, ei1, replacementText1);
            
            
            
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
            
            
            int startIndex = stringBufferOfData.indexOf(lineToEdit2);
//now we get the starting point of the text we want to edit
            int endIndex = startIndex + lineToEdit2.length();
//now we add the staring index of the text with text length to get the end index
            stringBufferOfData.replace(startIndex, endIndex, replacementText2);
            
          
                        try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            
//this is where the actual replacement of the text happens
            int si2 = stringBufferOfData.indexOf(p);
            int ei2 = si2+p.length();
            stringBufferOfData.replace(si2, ei2, rpin);
            
            
            
            
            try {
                BufferedWriter bufwriter = new BufferedWriter(new FileWriter(filename));
                bufwriter.write(stringBufferOfData.toString());//writes the edited string buffer to the new file
                bufwriter.close();//closes the file
            } catch (Exception e) {//if an exception occurs
                System.out.println("Error occured while attempting to write to file: " + e.getMessage());
            }
            
            
            
            //JOptionPane.showMessageDialog(null,"Balance transfer of  amount "+d+" Successfully!!!");
            moneytransfer rgf1=new moneytransfer(acc);
            rgf1.setVisible(true);
            rgf1.pack();
            rgf1.setLocationRelativeTo(null);
            rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();   
            return ;
        }
        
          /*  else{
            JOptionPane.showMessageDialog(null, "Invalid PIN number!!");
            WithdrawMoney rgf2=new WithdrawMoney(acc);
            rgf2.setVisible(true);
            rgf2.pack();
            rgf2.setLocationRelativeTo(null);
            rgf2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            return ;
        }*/
            
            
    }//GEN-LAST:event_balancesendActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Transaction rgf=new Transaction(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void reciveracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciveracActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reciveracActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String ac) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moneytransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moneytransfer(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balancesend;
    private javax.swing.JTextField enteramount;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pin;
    private javax.swing.JTextField reciverac;
    // End of variables declaration//GEN-END:variables
}
