
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class RegistrationForm extends javax.swing.JFrame {
    public int x,uppercase=0,lowercase=0;
     String uemail="",utext="Account Created Successfully\n";
     int f=0,sa=0;String sb="",transaction="";

    /**
     * Creates new form DepositeMoney
     */
    
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        pin = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        birthdate = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(125, 60, 152));
        jPanel2.setPreferredSize(new java.awt.Dimension(1241, 860));
        jPanel2.setLayout(null);

        name.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        name.setBorder(null);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(500, 80, 550, 50);

        pin.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        pin.setBorder(null);
        jPanel2.add(pin);
        pin.setBounds(500, 150, 550, 50);

        phone.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        phone.setBorder(null);
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel2.add(phone);
        phone.setBounds(500, 210, 550, 50);

        email.setFont(new java.awt.Font("Cooper Black", 3, 36)); // NOI18N
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(500, 270, 550, 50);

        birthdate.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        birthdate.setBorder(null);
        jPanel2.add(birthdate);
        birthdate.setBounds(500, 330, 550, 60);

        balance.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        balance.setBorder(null);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        jPanel2.add(balance);
        balance.setBounds(500, 400, 550, 60);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Your pin:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 140, 241, 41);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Phone:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 200, 204, 41);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Full Name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 80, 253, 41);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Birth Date:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 340, 266, 41);

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("First Deposit:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(110, 410, 314, 41);

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Email:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(110, 270, 204, 44);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Address :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 490, 225, 44);

        address.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        address.setBorder(null);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel2.add(address);
        address.setBounds(500, 480, 550, 160);

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("Back to Log In");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, new java.awt.Color(255, 0, 0), java.awt.Color.red, java.awt.Color.red));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(80, 690, 400, 70);

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        save.setForeground(new java.awt.Color(102, 255, 204));
        save.setText("Save");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(750, 690, 390, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designbig.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-10, 0, 1250, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        LoginForm rgf=new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   
         return ;
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String sp="";
        
        
        String ctime="";
        String t1="",t2="";
        SimpleDateFormat formatter= new SimpleDateFormat("'Date: 'yyyy-MM-dd 'Time: 'HH:mm:ss z");
        Date date = new Date(System.currentTimeMillis());
        ctime=formatter.format(date);
        int a=0;
        try {                                       
            // TODO add your handling code here: 
            
            if(f==0){
                f=1;
            String s12=""; 
            int p;
            FileInputStream fin = new FileInputStream("account.txt");
            
            
            
            while((p=fin.read())!=-1)
            {
               s12=s12+(char)p;
            }
            fin.close();
                 File f1=new File("account.txt"); 
            f1.delete();
            
       
            BufferedWriter out = new BufferedWriter(new FileWriter("account.txt",true));
           
            a=Integer.parseInt(s12);
            
            a++; 
            sa=a;
            sb=Integer.toString(a);
            
             utext=utext+"Account No : "+sb+"\n";
            out.write(sb);
            out.close();
                 transaction=sb;
            
            sb=sb+".txt";
            transaction=transaction+"t_h"+".txt";
            
        }
            
            
            
       
            
       
             FileOutputStream min= new FileOutputStream(transaction,true);
            FileOutputStream fout=new FileOutputStream(sb,true);
             //BufferedWriter mahedi = new BufferedWriter( new FileWriter(transaction, true)); 
         
            String x1="",x2="",x3="",x4="",x5="";
            String s1=name.getText();
            x1=s1;
            s1=s1+"\n";
             char ch1[]=s1.toCharArray();
            for(int i=0;i<s1.length();i++)
                fout.write(ch1[i]);
            String s2=pin.getText();
            sp=s2;
            x2=s2;
            
            
            s2=s2+"\n";
            for(int i=0;i<s2.length();i++)
            {
                if(Character.isLowerCase(s2.charAt(i))){
					lowercase++;
				}
				else if(Character.isUpperCase(s2.charAt(i))){
					uppercase++;
				}
            }
            char ch2[]=s2.toCharArray();
            for(int i=0;i<s2.length();i++)
                fout.write(ch2[i]);
            
            
            
               String s6=balance.getText();
              String x6=s6;
              t1=s6;
              s6=s6+"\n";
             char ch6[]=s6.toCharArray();
            for(int i=0;i<s6.length();i++)
                fout.write(ch6[i]);
            
            
            
            
            
              String s3=phone.getText();
              x3=s3;
              s3=s3+"\n";
            char ch3[]=s3.toCharArray();
            for(int i=0;i<s3.length();i++)
                fout.write(ch3[i]);
            
            
            
            
              String s4=email.getText();
              x4=s4;
              s4=s4+"\n";
              uemail=s4;
        
             char ch4[]=s4.toCharArray();
            for(int i=0;i<s4.length();i++)
                fout.write(ch4[i]);
            
            
            
            
            
              String s5=birthdate.getText();
              x5=s5;
              s5=s5+"\n";
             char ch5[]=s5.toCharArray();
            for(int i=0;i<s5.length();i++)
                fout.write(ch5[i]);
            
           
            
              String s7=address.getText();
              String x7=s7;
              s7=s7+"\n";
             char ch7[]=s7.toCharArray();
            for(int i=0;i<s7.length();i++)
                fout.write(ch7[i]);
            
            fout.close();
            t2=ctime+" "+t1+"Taka Has Been Deposited To Your Account"+"\n";
            char v2[]=t2.toCharArray();
            for(int i=0;i<v2.length;i++)
             min.write(v2[i]); 
            min.close(); 
            if(uppercase<1||lowercase<1||s2.length()<=6)
            {
                
                
                  File finn=new File(sb);
                  finn.delete();
                  BufferedWriter outt=new BufferedWriter(new FileWriter(transaction));
                  outt.close();
                  new File(transaction).delete();
               
                  try
                {
                    throw new Exception();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Pin should "
                            + "contain at leat one uppercase letter and "
                            + "one lowercase letter and should contain at least 6 cobination");
                    
                    return;
                }
                
            }
            if(x1.isEmpty()||x2.isEmpty()||x3.isEmpty()||x4.isEmpty()||x5.isEmpty()||x6.isEmpty()||x7.isEmpty())
            {
               
                  File finn=new File(sb);
                  finn.delete();
                  BufferedWriter outt=new BufferedWriter(new FileWriter(transaction));
                  outt.close();
                  new File(transaction).delete();
               
                  try
                {
                    throw new Exception();
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Information is missing!");
                 
                    
                    
                    return;
                }
            }
            else   
            utext=utext+"Pin no : "+sp+"\n";
        }
        
        catch (IOException e) {
         Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
        
             JOptionPane.showMessageDialog(null, "Registration Completed Successfully!!!\nYou account number is = "+(sa));
             
            class Main1
{
    String  d_email = "mh715360@gmail.com",
            d_password = "97325060",
            d_host = "smtp.gmail.com",
            d_port  = "465",
            m_to = uemail,
            m_subject = "Account verifiacation",
            m_text = utext;

    public Main1()
    {
        Properties props = new Properties();
        props.put("mail.smtp.user", d_email);
        props.put("mail.smtp.host", d_host);
        props.put("mail.smtp.port", d_port);
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", d_port);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");

        SecurityManager security = System.getSecurityManager();

        try
        {
            Authenticator auth = new SMTPAuthenticator();
            Session session = Session.getInstance(props, auth);
            session.setDebug(true);
            MimeMessage msg = new MimeMessage(session);
            msg.setText(m_text);
            msg.setSubject(m_subject);
            msg.setFrom(new InternetAddress(d_email));
            msg.addRecipient(Message.RecipientType.TO, new InternetAddress(m_to));
            Transport.send(msg);
        }
        catch (Exception mex)
        {
            mex.printStackTrace();
        } 
    }

    

    class SMTPAuthenticator extends javax.mail.Authenticator
    {
        public PasswordAuthentication getPasswordAuthentication()
        {
            return new PasswordAuthentication(d_email, d_password);
        }
    }
}
            
       
       Main1 blah = new Main1();
        
        
        
        
        LoginForm rgf=new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
        
            
    }//GEN-LAST:event_saveActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField email;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pin;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
