
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    public static String acc;
    public Transaction(String ac) {
        acc=ac;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonPinChange1 = new javax.swing.JButton();
        jButtonCashwithdraw = new javax.swing.JButton();
        jButtonDeposit = new javax.swing.JButton();
        jButtonBacttoLogin = new javax.swing.JButton();
        MiniStatement = new javax.swing.JButton();
        jButtonBalanceEnquiry = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1241, 860));
        jPanel1.setLayout(null);

        jButtonExit.setBackground(new java.awt.Color(102, 102, 102));
        jButtonExit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 0, 0));
        jButtonExit.setText("Exit");
        jButtonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit);
        jButtonExit.setBounds(110, 750, 390, 60);

        jButtonPinChange1.setBackground(new java.awt.Color(153, 255, 204));
        jButtonPinChange1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButtonPinChange1.setForeground(new java.awt.Color(102, 102, 102));
        jButtonPinChange1.setText("Pin Change");
        jButtonPinChange1.setAlignmentY(0.0F);
        jButtonPinChange1.setAutoscrolls(true);
        jButtonPinChange1.setBorder(null);
        jButtonPinChange1.setBorderPainted(false);
        jButtonPinChange1.setContentAreaFilled(false);
        jButtonPinChange1.setIconTextGap(0);
        jButtonPinChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPinChange1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPinChange1);
        jButtonPinChange1.setBounds(170, 370, 390, 50);

        jButtonCashwithdraw.setBackground(new java.awt.Color(153, 255, 204));
        jButtonCashwithdraw.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButtonCashwithdraw.setForeground(new java.awt.Color(102, 102, 102));
        jButtonCashwithdraw.setText("Cash Withdraw");
        jButtonCashwithdraw.setAlignmentY(0.0F);
        jButtonCashwithdraw.setAutoscrolls(true);
        jButtonCashwithdraw.setBorder(null);
        jButtonCashwithdraw.setBorderPainted(false);
        jButtonCashwithdraw.setContentAreaFilled(false);
        jButtonCashwithdraw.setIconTextGap(0);
        jButtonCashwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCashwithdrawActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCashwithdraw);
        jButtonCashwithdraw.setBounds(760, 290, 410, 60);

        jButtonDeposit.setBackground(new java.awt.Color(153, 255, 204));
        jButtonDeposit.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButtonDeposit.setForeground(new java.awt.Color(102, 102, 102));
        jButtonDeposit.setText("Deposit");
        jButtonDeposit.setAlignmentY(0.0F);
        jButtonDeposit.setAutoscrolls(true);
        jButtonDeposit.setBorder(null);
        jButtonDeposit.setBorderPainted(false);
        jButtonDeposit.setContentAreaFilled(false);
        jButtonDeposit.setIconTextGap(0);
        jButtonDeposit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeposit);
        jButtonDeposit.setBounds(760, 140, 390, 70);

        jButtonBacttoLogin.setBackground(new java.awt.Color(102, 102, 102));
        jButtonBacttoLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        jButtonBacttoLogin.setForeground(new java.awt.Color(153, 255, 255));
        jButtonBacttoLogin.setText("Back to Log In");
        jButtonBacttoLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        jButtonBacttoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBacttoLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBacttoLogin);
        jButtonBacttoLogin.setBounds(670, 750, 440, 60);

        MiniStatement.setBackground(new java.awt.Color(153, 255, 204));
        MiniStatement.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        MiniStatement.setForeground(new java.awt.Color(102, 102, 102));
        MiniStatement.setText("Account detail");
        MiniStatement.setAlignmentY(0.0F);
        MiniStatement.setAutoscrolls(true);
        MiniStatement.setBorder(null);
        MiniStatement.setBorderPainted(false);
        MiniStatement.setContentAreaFilled(false);
        MiniStatement.setIconTextGap(0);
        MiniStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiniStatementActionPerformed(evt);
            }
        });
        jPanel1.add(MiniStatement);
        MiniStatement.setBounds(120, 220, 480, 60);

        jButtonBalanceEnquiry.setBackground(new java.awt.Color(153, 255, 204));
        jButtonBalanceEnquiry.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButtonBalanceEnquiry.setForeground(new java.awt.Color(102, 102, 102));
        jButtonBalanceEnquiry.setText("Balance Enquiry");
        jButtonBalanceEnquiry.setAlignmentY(0.0F);
        jButtonBalanceEnquiry.setAutoscrolls(true);
        jButtonBalanceEnquiry.setBorder(null);
        jButtonBalanceEnquiry.setBorderPainted(false);
        jButtonBalanceEnquiry.setContentAreaFilled(false);
        jButtonBalanceEnquiry.setIconTextGap(0);
        jButtonBalanceEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalanceEnquiryActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBalanceEnquiry);
        jButtonBalanceEnquiry.setBounds(130, 70, 470, 60);

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Transaction history");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setIconTextGap(0);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 520, 520, 50);

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("fast cash");
        jButton2.setAlignmentY(0.0F);
        jButton2.setAutoscrolls(true);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setIconTextGap(0);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 590, 470, 60);

        jButton3.setBackground(new java.awt.Color(153, 255, 204));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 40)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("balance transfer");
        jButton3.setAlignmentY(0.0F);
        jButton3.setAutoscrolls(true);
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setIconTextGap(0);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(730, 430, 470, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0_MAIN_3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FastCash1 rgf1=new FastCash1(acc);
        rgf1.setVisible(true);
        rgf1.pack();
        rgf1.setLocationRelativeTo(null);
        rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TransactionHistory rgf1=new TransactionHistory(acc);
        rgf1.setVisible(true);
        rgf1.pack();
        rgf1.setLocationRelativeTo(null);
        rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBalanceEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalanceEnquiryActionPerformed
        // TODO add your handling code here:
        BalanceInquery rgf=new BalanceInquery(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButtonBalanceEnquiryActionPerformed

    private void MiniStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiniStatementActionPerformed
        // TODO add your handling code here:
        MiniStatement rgf=new MiniStatement(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_MiniStatementActionPerformed

    private void jButtonBacttoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBacttoLoginActionPerformed
        // TODO add your handling code here:
        LoginForm rgf=new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButtonBacttoLoginActionPerformed

    private void jButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositActionPerformed
        // TODO add your handling code here:
        DepositeMoney rgf1=new DepositeMoney(acc);
        rgf1.setVisible(true);
        rgf1.pack();
        rgf1.setLocationRelativeTo(null);
        rgf1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButtonDepositActionPerformed

    private void jButtonCashwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCashwithdrawActionPerformed
        // TODO add your handling code here:
        WithdrawMoney rgf=new WithdrawMoney(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButtonCashwithdrawActionPerformed

    private void jButtonPinChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinChange1ActionPerformed
        // TODO add your handling code here:
        PinChange rgf=new PinChange(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
    }//GEN-LAST:event_jButtonPinChange1ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Are you want to Exit!");
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        moneytransfer rgf=new moneytransfer(acc);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        return ;
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] arg) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String ac=null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction(ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MiniStatement;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBacttoLogin;
    private javax.swing.JButton jButtonBalanceEnquiry;
    private javax.swing.JButton jButtonCashwithdraw;
    private javax.swing.JButton jButtonDeposit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPinChange1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
